export const REGISTRATION_STARTED = "REGISTRATION_STARTED";
export const REGISTRATION_FINISHED = "REGISTRATION_FINISHED";
export const REGISTRATION_SUCCESSFUL = "REGISTRATION_SUCCESSFUL";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
