export const SUBMITTING_STARTED = 'SUBMITTING_STARTED';
export const SUBMISSION_SUCCESSFUL = 'SUBMISSION_SUCCESSFUL';
export const SUBMISSION_ERROR = 'SUBMISSION_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SWITCH_USER_AUTH_STATUS = 'SWITCH_USER_AUTH_STATUS';
