export const SUBMITTING_STARTED = 'SUBMITTING_STARTED';
export const GETTING_SHOPPINGLISTS_STARTED = 'GETTING_SHOPPINGLISTS_STARTED';
export const SUBMISSION_SUCCESSFUL = 'SUBMISSION_SUCCESSFUL';
export const SUBMISSION_ERROR = 'SUBMISSION_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SWITCH_USER_AUTH_STATUS = 'SWITCH_USER_AUTH_STATUS';
export const ERROR_ENCOUNTERED = 'ERROR_ENCOUNTERED';
export const SHOPPINGLISTS_LOADED_SUCCESSFULLY = 'SHOPPINGLISTS_LOADED_SUCCESSFULLY';
export const CREATING_SHOPPINGLISTS_STARTED = 'CREATING_SHOPPINGLISTS_STARTED';
export const SHOPPINGLISTS_CREATED_SUCCESSFULY = 'SHOPPINGLISTS_CREATED_SUCCESSFULY';
export const ACTIVATE_FAB = 'ACTIVATE_FAB';
export const DEACTIVATE_FAB = 'DEACTIVATE_FAB';
export const HIDE_SNACK_BAR = 'HIDE_SNACK_BAR';
export const OPEN_UPDATE_DIALOG = 'OPEN_UPDATE_DIALOG';
export const CLOSE_UPDATE_DIALOG = 'CLOSE_UPDATE_DIALOG';
export const SHOPPINGLISTS_DELETED_SUCCESSFULY = 'SHOPPINGLISTS_DELETED_SUCCESSFULY';
export const UPDATING_SHOPPINGLIST_STARTED = 'UPDATING_SHOPPINGLIST_STARTED';
export const SHOPPINGLISTS_UPDATED_SUCCESSFULY = 'SHOPPINGLISTS_UPDATED_SUCCESSFULY';

/**
 * Shoppinglist items
 */
export const ACTIVATE_ADD_ITEM = 'ACTIVATE_ADD_ITEM';
export const DEACTIVATE_ADD_ITEM = 'DEACTIVATE_ADD_ITEM';
export const ADDING_SHOPPINGLIST_ITEM_STARTED = 'ADDING_SHOPPINGLIST_ITEM_STARTED';
export const SHOPPINGLIST_ITEM_ADDED = 'SHOPPINGLIST_ITEM_ADDED';
export const SHOPPINGLIST_ITEMS_LOADING = 'SHOPPINGLIST_ITEMS_LOADING';
export const SHOPPINGLIST_ITEMS_FAILED = 'SHOPPINGLIST_ITEMS_FAILED';
export const SHOPPINGLIST_ITEMS_LOADED_SUCCESSFULLY = 'SHOPPINGLIST_ITEMS_LOADED_SUCCESSFULLY';
export const DELETING_ITEM_STARTED = 'DELETING_ITEM_STARTED';
export const ITEM_DELETED_SUCCESSFULLY = 'ITEM_DELETED_SUCCESSFULLY';
